---
format_version: 10
common:
  deploy-tasks: &deploy-tasks
    - exec:
        command: bash
        arguments:
          - -c
          - echo "Deployment to ${ENV_NAME} environment"
  test-tasks: &test-tasks
    - exec:
        command: bash
        arguments:
          - -c
          - echo "Testing in ${ENV_NAME}"
    - exec:
        command: bash
        arguments:
          - -c
          - docker run --network=host -d -t --name api_test_executor_CHANGED_${ENV_NAME} api_test_executor:latest
    - exec:
        command: bash
        arguments:
          - -c
          - docker exec api_test_executor_CHANGED_${ENV_NAME} cucumber --tags=@${ENV_NAME} --format html --out test-output/report.html
    - exec:
        command: bash
        arguments:
          - -c
          - docker cp api_test_executor_CHANGED_${ENV_NAME}:/usr/src/api-tests/test-output/report.html report_${ENV_NAME}.html
    - exec:
        command: bash
        arguments:
          - -c
          - docker rm -f api_test_executor_CHANGED_${ENV_NAME}
pipelines:
  node-microservice:
    group: microservices
    materials:
      gitrepo:
        git: https://github.com/baugistoms/ci_course.git
        branch: main
    stages:
      - build:
          jobs:
            build:
              tasks:
               - exec:
                   command: bash
                   arguments:
                      - -c
                      - echo "Building application"
      - deploy-dev:
          environment_variables:
              ENV_NAME: dev
          jobs:
            build:
              tasks: *deploy-tasks
      - test-dev:
          environment_variables:
            ENV_NAME: dev
          jobs:
            build:
              tasks: *test-tasks
      - deploy-int:
          environment_variables:
            ENV_NAME: int
          jobs:
            build:
              tasks: *deploy-tasks
      - test-int:
          environment_variables:
            ENV_NAME: int
          jobs:
            build:
              tasks: *test-tasks
      - deploy-prod:
          environment_variables:
            ENV_NAME: prod
          jobs:
            build:
              tasks: *deploy-tasks
      - test-prod:
          environment_variables:
            ENV_NAME: prod
          jobs:
            build:
              tasks: *test-tasks